### PR TITLE
Update the query processor and interface

### PR DESCRIPTION
**Pull request by surchs**
This will allow us to run queries on the new data model in the Graph. 
The main changes are: 
- the `create_query` method in `query/core.py` now creates an updated SPARQL query
- we have a new field for `"num_sessions"` in the interface that allows us to request a minimum number of sessions that fit the criteria
- the output of the downloadable data has been updated
- gender has been refactored to sex

Fixes: #119 
Fixes: #121 
Fixes: #95 

Known issues / fix later:
- the `query_interface/query_choices.py` file cannot be created automatically. `query/kg_helpers.py` is updated and works, but doesn't generate the required data because we haven't added human readable labels to entities in the graph yet: https://github.com/neurobagel/project/issues/47
- datasets don't have repository names yet: https://github.com/neurobagel/bagelbids/issues/23
- datasets also have useless names (all called BIDS): https://github.com/neurobagel/bagelbids/issues/23
- the downloadable results use URIs, not human readable labels. We'll have to figure out what users want here. I think for a first demo it's enough

### CODE REVIEW

**Comment by jarmoza** [comment]
@surchs Though I've forgotten a bunch of the  query language, from visual inspection of the code and my testing of the interface, all mostly looks well.

Two questions outstanding.

1. Now that you've established this 'healthy control' from Ontobee, what does it mean to be a healthy control and have a Parkinson's diagnosis? I noticed that this is not zero subjects
2. If converting terminology from 'gender' to 'sex', should we now just convert it throughout the interface/code?

**Review by jarmoza — COMMENTED** [review]
@surchs Though I've forgotten a bunch of the query language, from visual inspection of the code and my testing of the interface, all mostly looks well.

Two questions outstanding.

Now that you've established this 'healthy control' from Ontobee, what does it mean to be a healthy control and have a Parkinson's diagnosis? I noticed that this is not zero subjects
If converting terminology from 'gender' to 'sex', should we now just convert it throughout the interface/code?

**Comment by surchs** [comment]
Thanks @jarmoza, both good questions. 

> what does it mean to be a healthy control and have a Parkinson's diagnosis? I noticed that this is not zero subjects

If you select both a diagnosis and "control subject", the result is that both are ignored (see [here](https://github.com/neurobagel/concept_query/pull/122/files#diff-4a7c0c05332ca5c964a6bd0ba57e2c8664287d943ebe0205045779585af52f9dR37)). Ideally the interface should mention that - I'm a bit hesitant to implement that given our plans to change the whole thing. Maybe a text string could be added to clarify.

> should we now just convert it throughout the interface/code

Agreed, we should probably do that.

**Review by jarmoza — APPROVED** [review]
Looks good, @surchs. Plus the commenting out of caching.

**Pull request merged**
